"""Deterministic source compiler for the optional build123d CAD backend."""

from __future__ import annotations

import json

from app.models.cad import CadDocument, ProfileExtrusionBase, ProfileRevolutionBase
from app.services.profile_geometry import loop_bounds

_PAYLOAD_MARKER = "__PROMPTCAD_DOCUMENT_JSON__"
_PROFILE_EXTENTS_MARKER = "__PROMPTCAD_PROFILE_EXTENTS__"

_SCRIPT = r'''"""Generated by PromptCAD Studio for build123d."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from build123d import (
    Align,
    Axis,
    Box,
    Cone,
    Cylinder,
    Face,
    Line,
    Pos,
    Rot,
    ThreePointArc,
    Vector,
    Wire,
    chamfer,
    export_step,
    export_stl,
    extrude,
    fillet,
    revolve,
)

CAD_SPEC = json.loads(__PROMPTCAD_DOCUMENT_JSON__)
CAD_PROFILE_EXTENTS = json.loads(__PROMPTCAD_PROFILE_EXTENTS__)


def _extents(spec):
    base = spec["base"]
    kind = base["kind"]
    if kind == "plate":
        return base["length"] / 2, base["width"] / 2, base["thickness"]
    if kind == "cylinder":
        return base["diameter"] / 2, base["diameter"] / 2, base["height"]
    if kind == "ring":
        return base["outer_diameter"] / 2, base["outer_diameter"] / 2, base["height"]
    if kind == "l_bracket":
        return base["width"] / 2, base["depth"] / 2, base["vertical_height"] + base["thickness"]
    if kind == "enclosure":
        return base["length"] / 2, base["width"] / 2, base["height"]
    return tuple(CAD_PROFILE_EXTENTS)


def _base(spec):
    base = spec["base"]
    kind = base["kind"]
    center_xy_min_z = (Align.CENTER, Align.CENTER, Align.MIN)
    if kind == "plate":
        return Box(
            base["length"], base["width"], base["thickness"], align=center_xy_min_z
        )
    if kind == "cylinder":
        return Cylinder(base["diameter"] / 2, base["height"], align=center_xy_min_z)
    if kind == "ring":
        outer = Cylinder(base["outer_diameter"] / 2, base["height"], align=center_xy_min_z)
        inner = Cylinder(base["inner_diameter"] / 2, base["height"] + 2, align=center_xy_min_z)
        return outer - Pos(0, 0, -1) * inner
    if kind == "l_bracket":
        horizontal = Box(
            base["width"], base["depth"], base["thickness"], align=center_xy_min_z
        )
        vertical = Box(
            base["width"],
            base["thickness"],
            base["vertical_height"],
            align=center_xy_min_z,
        )
        vertical = Pos(
            0, -base["depth"] / 2 + base["thickness"] / 2, base["thickness"]
        ) * vertical
        return horizontal + vertical
    if kind == "enclosure":
        outer = Box(base["length"], base["width"], base["height"], align=center_xy_min_z)
        inner = Box(
            base["length"] - 2 * base["wall_thickness"],
            base["width"] - 2 * base["wall_thickness"],
            base["height"] - base["wall_thickness"] + 0.2,
            align=center_xy_min_z,
        )
        return outer - Pos(0, 0, base["wall_thickness"]) * inner
    if kind == "profile_extrusion":
        # build123d preserves authored lines and three-point arcs exactly.
        edges = []
        for segment in base["outer"]["segments"]:
            start = segment["start"]
            end = segment["end"]
            if segment["kind"] == "line":
                edges.append(
                    Line(
                        Vector(start["x"], start["y"], 0),
                        Vector(end["x"], end["y"], 0),
                    )
                )
            else:
                mid = segment["mid"]
                edges.append(
                    ThreePointArc(
                        Vector(start["x"], start["y"], 0),
                        Vector(mid["x"], mid["y"], 0),
                        Vector(end["x"], end["y"], 0),
                    )
                )
        return extrude(Face(Wire(edges)), amount=base["thickness"])
    if kind == "profile_revolution":
        # Point2D is (radius, z); author the exact wire in global XZ.
        edges = []
        for segment in base["outer"]["segments"]:
            start = segment["start"]
            end = segment["end"]
            if segment["kind"] == "line":
                edges.append(
                    Line(
                        Vector(start["x"], 0, start["y"]),
                        Vector(end["x"], 0, end["y"]),
                    )
                )
            else:
                mid = segment["mid"]
                edges.append(
                    ThreePointArc(
                        Vector(start["x"], 0, start["y"]),
                        Vector(mid["x"], 0, mid["y"]),
                        Vector(end["x"], 0, end["y"]),
                    )
                )
        return revolve(Face(Wire(edges)), axis=Axis.Z, revolution_arc=360)
    raise ValueError(f"unsupported base kind: {kind}")


def _oriented(shape, origin, direction):
    if direction == (1, 0, 0):
        shape = Rot(0, 90, 0) * shape
    elif direction == (-1, 0, 0):
        shape = Rot(0, -90, 0) * shape
    elif direction == (0, 1, 0):
        shape = Rot(-90, 0, 0) * shape
    elif direction == (0, -1, 0):
        shape = Rot(90, 0, 0) * shape
    elif direction == (0, 0, -1):
        shape = Rot(180, 0, 0) * shape
    return Pos(*origin) * shape


def _hole_path(hole, max_x, max_y, max_z):
    blind = hole["hole_type"] == "blind" and hole.get("depth") is not None
    axis = hole["axis"]
    if axis == "z":
        if blind:
            return (hole["x"], hole["y"], max_z + 0.1), (0, 0, -1), hole["depth"] + 0.2
        return (hole["x"], hole["y"], -1), (0, 0, 1), max_z + 2
    if axis == "x":
        if blind:
            return (max_x + 0.1, hole["y"], hole["z"]), (-1, 0, 0), hole["depth"] + 0.2
        return (-max_x - 1, hole["y"], hole["z"]), (1, 0, 0), 2 * max_x + 2
    if blind:
        return (hole["x"], max_y + 0.1, hole["z"]), (0, -1, 0), hole["depth"] + 0.2
    return (hole["x"], -max_y - 1, hole["z"]), (0, 1, 0), 2 * max_y + 2


def _positive_face(hole, max_x, max_y, max_z):
    if hole["axis"] == "z":
        return (hole["x"], hole["y"], max_z), (0, 0, -1)
    if hole["axis"] == "x":
        return (max_x, hole["y"], hole["z"]), (-1, 0, 0)
    return (hole["x"], max_y, hole["z"]), (0, -1, 0)


def _move_outward(origin, direction, amount):
    return tuple(origin[index] - direction[index] * amount for index in range(3))


def _cut_holes(result, spec, warnings):
    max_x, max_y, max_z = _extents(spec)
    center_xy_min_z = (Align.CENTER, Align.CENTER, Align.MIN)
    for index, hole in enumerate(spec["holes"]):
        origin, direction, height = _hole_path(hole, max_x, max_y, max_z)
        cutter = Cylinder(hole["diameter"] / 2, height, align=center_xy_min_z)
        result -= _oriented(cutter, origin, direction)
        face_origin, inward = _positive_face(hole, max_x, max_y, max_z)
        if hole["hole_type"] == "counterbore":
            start = _move_outward(face_origin, inward, 0.1)
            counterbore = Cylinder(
                hole["counterbore_diameter"] / 2,
                hole["counterbore_depth"] + 0.2,
                align=center_xy_min_z,
            )
            result -= _oriented(counterbore, start, inward)
        elif hole["hole_type"] == "countersink":
            depth = (hole["countersink_diameter"] - hole["diameter"]) / (
                2 * max(0.01, math.tan(math.radians(hole["countersink_angle"] / 2)))
            )
            countersink = Cone(
                hole["countersink_diameter"] / 2,
                hole["diameter"] / 2,
                depth,
                align=center_xy_min_z,
            )
            result -= _oriented(countersink, face_origin, inward)
        if hole["hole_type"] == "tapped":
            warnings.append(
                f"hole {index + 1}: thread metadata is preserved in CAD_SPEC; "
                "geometry uses the nominal diameter"
            )
    return result


def _cut_rectangles(result, spec):
    max_x, max_y, _ = _extents(spec)
    for cutout in spec["cutouts"]:
        if spec["base"]["kind"] == "enclosure":
            depth = spec["base"]["wall_thickness"]
        elif cutout["face"] in {"positive_x", "negative_x"}:
            depth = max_x * 2
        else:
            depth = max_y * 2
        cutter_depth = depth + 0.4
        if cutout["face"] == "positive_x":
            dimensions = (cutter_depth, cutout["width"], cutout["height"])
            center = (max_x - depth / 2, cutout["y"], cutout["z"])
        elif cutout["face"] == "negative_x":
            dimensions = (cutter_depth, cutout["width"], cutout["height"])
            center = (-max_x + depth / 2, cutout["y"], cutout["z"])
        elif cutout["face"] == "positive_y":
            dimensions = (cutout["width"], cutter_depth, cutout["height"])
            center = (cutout["x"], max_y - depth / 2, cutout["z"])
        else:
            dimensions = (cutout["width"], cutter_depth, cutout["height"])
            center = (cutout["x"], -max_y + depth / 2, cutout["z"])
        cutter = Box(*dimensions, align=(Align.CENTER, Align.CENTER, Align.CENTER))
        result -= Pos(*center) * cutter
    return result


def _selected_edges(result, selector):
    if selector == "all":
        return result.edges()
    if selector == "vertical":
        return result.edges().filter_by(Axis.Z)
    groups = result.edges().group_by(Axis.Z)
    return groups[-1] if selector == "top" else groups[0]


def build():
    warnings = []
    result = _cut_rectangles(_cut_holes(_base(CAD_SPEC), CAD_SPEC, warnings), CAD_SPEC)
    for feature in CAD_SPEC["fillets"]:
        result = fillet(
            _selected_edges(result, feature["selector"]), radius=feature["radius"]
        )
    for feature in CAD_SPEC["chamfers"]:
        result = chamfer(
            _selected_edges(result, feature["selector"]), length=feature["distance"]
        )
    return result, warnings


def export_all(result, output_dir, formats, warnings):
    output_dir.mkdir(parents=True, exist_ok=True)
    if "step" in formats:
        path = output_dir / "model.step"
        export_step(result, path)
        if not path.is_file() or path.stat().st_size == 0:
            raise RuntimeError("build123d STEP exporter did not produce a file")
    if "stl" in formats:
        path = output_dir / "model.stl"
        export_stl(
            result,
            path,
            tolerance=0.05,
            angular_tolerance=0.1,
        )
        if not path.is_file() or path.stat().st_size == 0:
            raise RuntimeError("build123d STL exporter did not produce a file")
    (output_dir / "render-warnings.json").write_text(
        json.dumps(warnings, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def main():
    parser = argparse.ArgumentParser(description="Render a validated PromptCAD document")
    parser.add_argument("--output-dir", type=Path, default=Path("."))
    parser.add_argument(
        "--formats", nargs="+", choices=("step", "stl"), default=("step", "stl")
    )
    args = parser.parse_args()
    result, warnings = build()
    export_all(result, args.output_dir, set(args.formats), warnings)


if __name__ == "__main__":
    main()
'''


class Build123dCompiler:
    """Compile a validated CAD document into a standalone build123d script."""

    def compile(self, doc: CadDocument) -> str:
        payload = json.dumps(
            doc.model_dump(mode="json"),
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
        profile_extents = None
        if isinstance(doc.base, ProfileExtrusionBase):
            min_x, min_y, max_x, max_y = loop_bounds(doc.base.outer)
            profile_extents = [
                max(abs(min_x), abs(max_x)),
                max(abs(min_y), abs(max_y)),
                doc.base.thickness,
            ]
        elif isinstance(doc.base, ProfileRevolutionBase):
            _, _, max_radius, max_z = loop_bounds(doc.base.outer)
            profile_extents = [max_radius, max_radius, max_z]
        extents_payload = json.dumps(profile_extents, separators=(",", ":"))
        return _SCRIPT.replace(
            _PROFILE_EXTENTS_MARKER,
            repr(extents_payload),
            1,
        ).replace(_PAYLOAD_MARKER, repr(payload), 1)
