from __future__ import annotations

import json
import math

from app.models.cad import (
    Axis,
    CadDocument,
    CylinderBase,
    EdgeSelector,
    EnclosureBase,
    HoleType,
    LBracketBase,
    PlateBase,
    ProfileExtrusionBase,
    ProfileRevolutionBase,
    RectangularCutoutFeature,
    RingBase,
    SideFace,
)
from app.services.profile_geometry import loop_bounds


def _f(value: float) -> str:
    return format(float(value), ".12g")


class CadQueryCompiler:
    def compile(self, doc: CadDocument) -> str:
        max_x, max_y, max_z = self._extents(doc)
        lines = [
            '"""Generated by PromptCAD Studio. Edit numeric parameters, then run this file."""',
            "from __future__ import annotations",
            "",
            "import argparse",
            "import json",
            "from pathlib import Path",
            "",
            "import cadquery as cq",
            "",
            f"CAD_SPEC = json.loads({json.dumps(doc.model_dump(mode='json'), ensure_ascii=False, indent=2)!r})",
            "",
            "",
            "def build():",
            "    warnings = []",
        ]
        lines.extend(self._base_lines(doc))
        for index, hole in enumerate(doc.holes):
            lines.extend(self._hole_lines(index, hole, max_x, max_y, max_z))
        for index, cutout in enumerate(doc.cutouts):
            lines.extend(self._cutout_lines(doc, index, cutout, max_x, max_y))
        for fillet in doc.fillets:
            selector = self._selector(fillet.selector)
            lines.append(
                f"    result = result.edges({selector!r}).fillet({_f(fillet.radius)})"
            )
        for chamfer in doc.chamfers:
            selector = self._selector(chamfer.selector)
            lines.append(
                f"    result = result.edges({selector!r}).chamfer({_f(chamfer.distance)})"
            )
        lines.extend(
            [
                "    return result, warnings",
                "",
                "",
                "def export_all(result, output_dir: Path, formats: set[str], warnings: list[str]):",
                "    output_dir.mkdir(parents=True, exist_ok=True)",
                "    if 'step' in formats:",
                "        result.export(str(output_dir / 'model.step'))",
                "    if 'stl' in formats:",
                "        result.export(str(output_dir / 'model.stl'), tolerance=0.05, angularTolerance=0.1)",
                "    if 'svg' in formats:",
                "        result.export(str(output_dir / 'model.svg'), opt={",
                "            'width': 900, 'height': 650, 'marginLeft': 20, 'marginTop': 20,",
                "            'showAxes': False, 'projectionDir': (1, -1, 0.75),",
                "            'showHidden': True, 'strokeWidth': 0.7,",
                "        })",
                "    if 'dxf' in formats:",
                "        try:",
                f"            section = result.section({_f(max_z / 2)})",
                "            section.export(str(output_dir / 'model.dxf'), opt={'approx': 'arc', 'tolerance': 0.01})",
                "        except Exception as exc:",
                "            warnings.append('DXF section export skipped: ' + str(exc))",
                "    (output_dir / 'render-warnings.json').write_text(",
                "        json.dumps(warnings, ensure_ascii=False, indent=2), encoding='utf-8'",
                "    )",
                "",
                "",
                "def main():",
                "    parser = argparse.ArgumentParser()",
                "    parser.add_argument('--output-dir', default='.')",
                "    parser.add_argument('--formats', nargs='*', default=['step', 'stl', 'dxf', 'svg'])",
                "    args = parser.parse_args()",
                "    result, warnings = build()",
                "    export_all(result, Path(args.output_dir), set(args.formats), warnings)",
                "",
                "",
                "if __name__ == '__main__':",
                "    main()",
                "",
            ]
        )
        return "\n".join(lines)

    def _base_lines(self, doc: CadDocument) -> list[str]:
        b = doc.base
        if isinstance(b, PlateBase):
            return [
                f"    result = cq.Workplane('XY').box({_f(b.length)}, {_f(b.width)}, {_f(b.thickness)}, centered=(True, True, False))"
            ]
        if isinstance(b, CylinderBase):
            return [f"    result = cq.Workplane('XY').circle({_f(b.diameter / 2)}).extrude({_f(b.height)})"]
        if isinstance(b, RingBase):
            return [
                f"    result = cq.Workplane('XY').circle({_f(b.outer_diameter / 2)}).circle({_f(b.inner_diameter / 2)}).extrude({_f(b.height)})"
            ]
        if isinstance(b, LBracketBase):
            return [
                f"    base_plate = cq.Workplane('XY').box({_f(b.width)}, {_f(b.depth)}, {_f(b.thickness)}, centered=(True, True, False))",
                f"    vertical = cq.Workplane('XY').box({_f(b.width)}, {_f(b.thickness)}, {_f(b.vertical_height)}, centered=(True, True, False)).translate((0, {_f(-b.depth / 2 + b.thickness / 2)}, {_f(b.thickness)}))",
                "    result = base_plate.union(vertical)",
            ]
        if isinstance(b, EnclosureBase):
            inner_l = b.length - 2 * b.wall_thickness
            inner_w = b.width - 2 * b.wall_thickness
            inner_h = b.height - b.wall_thickness
            return [
                f"    outer = cq.Workplane('XY').box({_f(b.length)}, {_f(b.width)}, {_f(b.height)}, centered=(True, True, False))",
                f"    inner = cq.Workplane('XY').box({_f(inner_l)}, {_f(inner_w)}, {_f(inner_h + 0.2)}, centered=(True, True, False)).translate((0, 0, {_f(b.wall_thickness)}))",
                "    result = outer.cut(inner)",
            ]
        if isinstance(b, ProfileExtrusionBase):
            first = b.outer.segments[0].start
            lines = [
                f"    profile = cq.Workplane('XY').moveTo({_f(first.x)}, {_f(first.y)})"
            ]
            for segment in b.outer.segments:
                if segment.kind == "line":
                    lines.append(
                        f"    profile = profile.lineTo({_f(segment.end.x)}, {_f(segment.end.y)})"
                    )
                else:
                    lines.append(
                        "    profile = profile.threePointArc("
                        f"({_f(segment.mid.x)}, {_f(segment.mid.y)}), "
                        f"({_f(segment.end.x)}, {_f(segment.end.y)}))"
                    )
            lines.append(f"    result = profile.close().extrude({_f(b.thickness)})")
            return lines
        if isinstance(b, ProfileRevolutionBase):
            first = b.outer.segments[0].start
            lines = [
                f"    profile = cq.Workplane('XZ').moveTo({_f(first.x)}, {_f(first.y)})"
            ]
            for segment in b.outer.segments:
                if segment.kind == "line":
                    lines.append(
                        f"    profile = profile.lineTo({_f(segment.end.x)}, {_f(segment.end.y)})"
                    )
                else:
                    lines.append(
                        "    profile = profile.threePointArc("
                        f"({_f(segment.mid.x)}, {_f(segment.mid.y)}), "
                        f"({_f(segment.end.x)}, {_f(segment.end.y)}))"
                    )
            lines.append(
                "    result = profile.close().revolve("
                "360, axisStart=(0, 0), axisEnd=(0, 1), combine=True, clean=True)"
            )
            return lines
        raise TypeError(f"Unsupported base: {type(b)!r}")

    @staticmethod
    def _cutout_lines(
        doc: CadDocument,
        index: int,
        cutout: RectangularCutoutFeature,
        max_x: float,
        max_y: float,
    ) -> list[str]:
        if isinstance(doc.base, EnclosureBase):
            depth = doc.base.wall_thickness
        elif cutout.face in {SideFace.POSITIVE_X, SideFace.NEGATIVE_X}:
            depth = max_x * 2
        else:
            depth = max_y * 2

        cutter_depth = depth + 0.4
        if cutout.face == SideFace.POSITIVE_X:
            dimensions = cutter_depth, cutout.width, cutout.height
            center = max_x - depth / 2, cutout.y, cutout.z
        elif cutout.face == SideFace.NEGATIVE_X:
            dimensions = cutter_depth, cutout.width, cutout.height
            center = -max_x + depth / 2, cutout.y, cutout.z
        elif cutout.face == SideFace.POSITIVE_Y:
            dimensions = cutout.width, cutter_depth, cutout.height
            center = cutout.x, max_y - depth / 2, cutout.z
        else:
            dimensions = cutout.width, cutter_depth, cutout.height
            center = cutout.x, -max_y + depth / 2, cutout.z

        return [
            f"    cutout_{index} = cq.Workplane('XY').box({_f(dimensions[0])}, "
            f"{_f(dimensions[1])}, {_f(dimensions[2])}, centered=(True, True, True))"
            f".translate(({_f(center[0])}, {_f(center[1])}, {_f(center[2])}))",
            f"    result = result.cut(cutout_{index})",
        ]

    def _hole_lines(self, index, hole, max_x, max_y, max_z) -> list[str]:
        origin, direction, distance = self._main_hole_cutter(hole, max_x, max_y, max_z)
        lines = [
            f"    hole_{index} = cq.Solid.makeCylinder({_f(hole.diameter / 2)}, {_f(distance)}, "
            f"cq.Vector({_f(origin[0])}, {_f(origin[1])}, {_f(origin[2])}), cq.Vector({_f(direction[0])}, {_f(direction[1])}, {_f(direction[2])}))",
            f"    result = result.cut(hole_{index})",
        ]

        face_origin, inward = self._positive_face(hole, max_x, max_y, max_z)
        if (
            hole.hole_type == HoleType.COUNTERBORE
            and hole.counterbore_diameter
            and hole.counterbore_depth
        ):
            start = tuple(
                face_origin[i] - inward[i] * 0.1
                for i in range(3)
            )
            lines.extend(
                [
                    f"    cbore_{index} = cq.Solid.makeCylinder({_f(hole.counterbore_diameter / 2)}, {_f(hole.counterbore_depth + 0.2)}, "
                    f"cq.Vector({_f(start[0])}, {_f(start[1])}, {_f(start[2])}), cq.Vector({_f(inward[0])}, {_f(inward[1])}, {_f(inward[2])}))",
                    f"    result = result.cut(cbore_{index})",
                ]
            )
        if (
            hole.hole_type == HoleType.COUNTERSINK
            and hole.countersink_diameter
            and hole.countersink_angle
        ):
            depth = (hole.countersink_diameter - hole.diameter) / (
                2 * max(0.01, math.tan(math.radians(hole.countersink_angle / 2)))
            )
            lines.extend(
                [
                    f"    csk_{index} = cq.Solid.makeCone({_f(hole.countersink_diameter / 2)}, {_f(hole.diameter / 2)}, {_f(depth)}, "
                    f"cq.Vector({_f(face_origin[0])}, {_f(face_origin[1])}, {_f(face_origin[2])}), cq.Vector({_f(inward[0])}, {_f(inward[1])}, {_f(inward[2])}))",
                    f"    result = result.cut(csk_{index})",
                ]
            )
        return lines

    @staticmethod
    def _main_hole_cutter(hole, max_x, max_y, max_z):
        blind = hole.hole_type == HoleType.BLIND and hole.depth is not None
        if hole.axis == Axis.Z:
            if blind:
                return (hole.x, hole.y, max_z + 0.1), (0.0, 0.0, -1.0), hole.depth + 0.2
            return (hole.x, hole.y, -1.0), (0.0, 0.0, 1.0), max_z + 2.0
        if hole.axis == Axis.X:
            if blind:
                return (max_x + 0.1, hole.y, hole.z), (-1.0, 0.0, 0.0), hole.depth + 0.2
            return (-max_x - 1.0, hole.y, hole.z), (1.0, 0.0, 0.0), 2 * max_x + 2.0
        if blind:
            return (hole.x, max_y + 0.1, hole.z), (0.0, -1.0, 0.0), hole.depth + 0.2
        return (hole.x, -max_y - 1.0, hole.z), (0.0, 1.0, 0.0), 2 * max_y + 2.0

    @staticmethod
    def _positive_face(hole, max_x, max_y, max_z):
        if hole.axis == Axis.Z:
            return (hole.x, hole.y, max_z), (0.0, 0.0, -1.0)
        if hole.axis == Axis.X:
            return (max_x, hole.y, hole.z), (-1.0, 0.0, 0.0)
        return (hole.x, max_y, hole.z), (0.0, -1.0, 0.0)

    @staticmethod
    def _selector(selector: EdgeSelector) -> str | None:
        return {
            EdgeSelector.ALL: None,
            EdgeSelector.VERTICAL: "|Z",
            EdgeSelector.TOP: ">Z",
            EdgeSelector.BOTTOM: "<Z",
        }[selector]

    @staticmethod
    def _extents(doc: CadDocument) -> tuple[float, float, float]:
        b = doc.base
        if isinstance(b, PlateBase):
            return b.length / 2, b.width / 2, b.thickness
        if isinstance(b, CylinderBase):
            return b.diameter / 2, b.diameter / 2, b.height
        if isinstance(b, RingBase):
            return b.outer_diameter / 2, b.outer_diameter / 2, b.height
        if isinstance(b, LBracketBase):
            return b.width / 2, b.depth / 2, b.vertical_height + b.thickness
        if isinstance(b, ProfileExtrusionBase):
            min_x, min_y, max_x, max_y = loop_bounds(b.outer)
            return max(abs(min_x), abs(max_x)), max(abs(min_y), abs(max_y)), b.thickness
        if isinstance(b, ProfileRevolutionBase):
            _, _, max_radius, max_z = loop_bounds(b.outer)
            return max_radius, max_radius, max_z
        return b.length / 2, b.width / 2, b.height
