"""Deterministic source compiler for the optional FreeCAD backend."""

from __future__ import annotations

import json

from app.models.cad import CadDocument, ProfileExtrusionBase, ProfileRevolutionBase
from app.services.profile_geometry import loop_bounds

_PAYLOAD_MARKER = "__PROMPTCAD_DOCUMENT_JSON__"
_PROFILE_EXTENTS_MARKER = "__PROMPTCAD_PROFILE_EXTENTS__"

_SCRIPT = r'''"""Generated by PromptCAD Studio for FreeCAD 1.x."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import FreeCAD as App
import Mesh
import Part

CAD_SPEC = json.loads(__PROMPTCAD_DOCUMENT_JSON__)
CAD_PROFILE_EXTENTS = json.loads(__PROMPTCAD_PROFILE_EXTENTS__)


def _vector(point, z=0):
    return App.Vector(point["x"], point["y"], z)


def _extents(spec):
    base = spec["base"]
    kind = base["kind"]
    if kind == "plate":
        return base["length"] / 2, base["width"] / 2, base["thickness"]
    if kind == "cylinder":
        return base["diameter"] / 2, base["diameter"] / 2, base["height"]
    if kind == "ring":
        return base["outer_diameter"] / 2, base["outer_diameter"] / 2, base["height"]
    if kind == "l_bracket":
        return base["width"] / 2, base["depth"] / 2, base["vertical_height"] + base["thickness"]
    if kind == "enclosure":
        return base["length"] / 2, base["width"] / 2, base["height"]
    return tuple(CAD_PROFILE_EXTENTS)


def _base(spec):
    base = spec["base"]
    kind = base["kind"]
    if kind == "plate":
        return Part.makeBox(
            base["length"],
            base["width"],
            base["thickness"],
            App.Vector(-base["length"] / 2, -base["width"] / 2, 0),
        )
    if kind == "cylinder":
        return Part.makeCylinder(base["diameter"] / 2, base["height"])
    if kind == "ring":
        return Part.makeCylinder(base["outer_diameter"] / 2, base["height"]).cut(
            Part.makeCylinder(base["inner_diameter"] / 2, base["height"] + 2, App.Vector(0, 0, -1))
        )
    if kind == "l_bracket":
        horizontal = Part.makeBox(
            base["width"],
            base["depth"],
            base["thickness"],
            App.Vector(-base["width"] / 2, -base["depth"] / 2, 0),
        )
        vertical = Part.makeBox(
            base["width"],
            base["thickness"],
            base["vertical_height"],
            App.Vector(-base["width"] / 2, -base["depth"] / 2, base["thickness"]),
        )
        return horizontal.fuse(vertical)
    if kind == "enclosure":
        outer = Part.makeBox(
            base["length"],
            base["width"],
            base["height"],
            App.Vector(-base["length"] / 2, -base["width"] / 2, 0),
        )
        inner = Part.makeBox(
            base["length"] - 2 * base["wall_thickness"],
            base["width"] - 2 * base["wall_thickness"],
            base["height"] - base["wall_thickness"] + 0.2,
            App.Vector(
                -base["length"] / 2 + base["wall_thickness"],
                -base["width"] / 2 + base["wall_thickness"],
                base["wall_thickness"],
            ),
        )
        return outer.cut(inner)
    if kind == "profile_extrusion":
        # FreeCAD's Part kernel keeps both lines and three-point arcs exact.
        edges = []
        for segment in base["outer"]["segments"]:
            if segment["kind"] == "line":
                edges.append(Part.makeLine(_vector(segment["start"]), _vector(segment["end"])))
            else:
                edges.append(
                    Part.Arc(
                        _vector(segment["start"]),
                        _vector(segment["mid"]),
                        _vector(segment["end"]),
                    ).toShape()
                )
        return Part.Face(Part.Wire(edges)).extrude(App.Vector(0, 0, base["thickness"]))
    if kind == "profile_revolution":
        # Point2D is (radius, z); preserve authored edges in global XZ.
        edges = []
        for segment in base["outer"]["segments"]:
            start = segment["start"]
            end = segment["end"]
            start_xz = App.Vector(start["x"], 0, start["y"])
            end_xz = App.Vector(end["x"], 0, end["y"])
            if segment["kind"] == "line":
                edges.append(Part.makeLine(start_xz, end_xz))
            else:
                mid = segment["mid"]
                edges.append(
                    Part.Arc(
                        start_xz,
                        App.Vector(mid["x"], 0, mid["y"]),
                        end_xz,
                    ).toShape()
                )
        face = Part.Face(Part.Wire(edges))
        return face.revolve(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 360)
    raise ValueError(f"unsupported base kind: {kind}")


def _hole_path(hole, max_x, max_y, max_z):
    blind = hole["hole_type"] == "blind" and hole.get("depth") is not None
    axis = hole["axis"]
    if axis == "z":
        if blind:
            return (hole["x"], hole["y"], max_z + 0.1), (0, 0, -1), hole["depth"] + 0.2
        return (hole["x"], hole["y"], -1), (0, 0, 1), max_z + 2
    if axis == "x":
        if blind:
            return (max_x + 0.1, hole["y"], hole["z"]), (-1, 0, 0), hole["depth"] + 0.2
        return (-max_x - 1, hole["y"], hole["z"]), (1, 0, 0), 2 * max_x + 2
    if blind:
        return (hole["x"], max_y + 0.1, hole["z"]), (0, -1, 0), hole["depth"] + 0.2
    return (hole["x"], -max_y - 1, hole["z"]), (0, 1, 0), 2 * max_y + 2


def _positive_face(hole, max_x, max_y, max_z):
    if hole["axis"] == "z":
        return (hole["x"], hole["y"], max_z), (0, 0, -1)
    if hole["axis"] == "x":
        return (max_x, hole["y"], hole["z"]), (-1, 0, 0)
    return (hole["x"], max_y, hole["z"]), (0, -1, 0)


def _move_outward(origin, direction, amount):
    return tuple(origin[index] - direction[index] * amount for index in range(3))


def _cylinder(radius, height, origin, direction):
    return Part.makeCylinder(radius, height, App.Vector(*origin), App.Vector(*direction))


def _cut_holes(result, spec, warnings):
    max_x, max_y, max_z = _extents(spec)
    for index, hole in enumerate(spec["holes"]):
        origin, direction, height = _hole_path(hole, max_x, max_y, max_z)
        result = result.cut(_cylinder(hole["diameter"] / 2, height, origin, direction))
        face_origin, inward = _positive_face(hole, max_x, max_y, max_z)
        if hole["hole_type"] == "counterbore":
            start = _move_outward(face_origin, inward, 0.1)
            result = result.cut(
                _cylinder(
                    hole["counterbore_diameter"] / 2,
                    hole["counterbore_depth"] + 0.2,
                    start,
                    inward,
                )
            )
        elif hole["hole_type"] == "countersink":
            depth = (hole["countersink_diameter"] - hole["diameter"]) / (
                2 * max(0.01, math.tan(math.radians(hole["countersink_angle"] / 2)))
            )
            result = result.cut(
                Part.makeCone(
                    hole["countersink_diameter"] / 2,
                    hole["diameter"] / 2,
                    depth,
                    App.Vector(*face_origin),
                    App.Vector(*inward),
                )
            )
        if hole["hole_type"] == "tapped":
            warnings.append(
                f"hole {index + 1}: thread metadata is preserved in CAD_SPEC; "
                "geometry uses the nominal diameter"
            )
    return result


def _cut_rectangles(result, spec):
    max_x, max_y, _ = _extents(spec)
    for cutout in spec["cutouts"]:
        if spec["base"]["kind"] == "enclosure":
            depth = spec["base"]["wall_thickness"]
        elif cutout["face"] in {"positive_x", "negative_x"}:
            depth = max_x * 2
        else:
            depth = max_y * 2
        cutter_depth = depth + 0.4
        if cutout["face"] == "positive_x":
            dimensions = (cutter_depth, cutout["width"], cutout["height"])
            center = (max_x - depth / 2, cutout["y"], cutout["z"])
        elif cutout["face"] == "negative_x":
            dimensions = (cutter_depth, cutout["width"], cutout["height"])
            center = (-max_x + depth / 2, cutout["y"], cutout["z"])
        elif cutout["face"] == "positive_y":
            dimensions = (cutout["width"], cutter_depth, cutout["height"])
            center = (cutout["x"], max_y - depth / 2, cutout["z"])
        else:
            dimensions = (cutout["width"], cutter_depth, cutout["height"])
            center = (cutout["x"], -max_y + depth / 2, cutout["z"])
        origin = tuple(center[index] - dimensions[index] / 2 for index in range(3))
        result = result.cut(Part.makeBox(*dimensions, App.Vector(*origin)))
    return result


def _selected_edges(result, selector):
    if selector == "all":
        return result.Edges
    if selector == "vertical":
        return [
            edge
            for edge in result.Edges
            if abs(edge.Vertexes[-1].Point.z - edge.Vertexes[0].Point.z) > 1e-7
        ]
    target = result.BoundBox.ZMax if selector == "top" else result.BoundBox.ZMin
    return [
        edge
        for edge in result.Edges
        if all(abs(vertex.Point.z - target) <= 1e-7 for vertex in edge.Vertexes)
    ]


def build():
    warnings = []
    result = _cut_rectangles(_cut_holes(_base(CAD_SPEC), CAD_SPEC, warnings), CAD_SPEC)
    for feature in CAD_SPEC["fillets"]:
        result = result.makeFillet(
            feature["radius"], _selected_edges(result, feature["selector"])
        )
    for feature in CAD_SPEC["chamfers"]:
        result = result.makeChamfer(
            feature["distance"], _selected_edges(result, feature["selector"])
        )
    return result, warnings


def export_all(shape, output_dir, formats, warnings):
    output_dir.mkdir(parents=True, exist_ok=True)
    document = App.newDocument("PromptCAD")
    feature = document.addObject("Part::Feature", "PromptCADPart")
    feature.Label = CAD_SPEC["name"]
    feature.Shape = shape
    document.recompute()
    if "step" in formats:
        Part.export([feature], str(output_dir / "model.step"))
    if "stl" in formats:
        Mesh.export([feature], str(output_dir / "model.stl"))
    if "fcstd" in formats:
        document.saveAs(str(output_dir / "model.FCStd"))
    (output_dir / "render-warnings.json").write_text(
        json.dumps(warnings, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def main():
    parser = argparse.ArgumentParser(description="Render a validated PromptCAD document")
    parser.add_argument("--output-dir", type=Path, default=Path("."))
    parser.add_argument(
        "--formats",
        nargs="+",
        choices=("step", "stl", "fcstd"),
        default=("step", "stl"),
    )
    args = parser.parse_args()
    result, warnings = build()
    export_all(result, args.output_dir, set(args.formats), warnings)


if __name__ == "__main__":
    main()
'''


class FreeCADCompiler:
    """Compile a validated CAD document into a standalone FreeCAD script."""

    def compile(self, doc: CadDocument) -> str:
        payload = json.dumps(
            doc.model_dump(mode="json"),
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
        profile_extents = None
        if isinstance(doc.base, ProfileExtrusionBase):
            min_x, min_y, max_x, max_y = loop_bounds(doc.base.outer)
            profile_extents = [
                max(abs(min_x), abs(max_x)),
                max(abs(min_y), abs(max_y)),
                doc.base.thickness,
            ]
        elif isinstance(doc.base, ProfileRevolutionBase):
            _, _, max_radius, max_z = loop_bounds(doc.base.outer)
            profile_extents = [max_radius, max_radius, max_z]
        extents_payload = json.dumps(profile_extents, separators=(",", ":"))
        return _SCRIPT.replace(
            _PROFILE_EXTENTS_MARKER,
            repr(extents_payload),
            1,
        ).replace(_PAYLOAD_MARKER, repr(payload), 1)


FreeCadCompiler = FreeCADCompiler
