from __future__ import annotations

import math

from app.models.cad import (
    CadDocument,
    CylinderBase,
    EnclosureBase,
    LBracketBase,
    PlateBase,
    ProfileExtrusionBase,
    RectangularCutoutFeature,
    RingBase,
    SideFace,
)
from app.services.profile_geometry import loop_bounds, loop_polyline


def _f(value: float) -> str:
    return format(float(value), ".12g")


class OpenScadCompiler:
    def compile(self, doc: CadDocument) -> str:
        lines = [
            "// Generated by PromptCAD Studio",
            "$fn = 96;",
            "",
            "difference() {",
            "  union() {",
        ]
        lines.extend(self._base(doc, indent="    "))
        lines.extend(["  }", "  union() {"])
        max_x, max_y, max_z = self._extents(doc)
        for hole in doc.holes:
            origin, rotation, length = self._main_hole_cutter(hole, max_x, max_y, max_z)
            lines.append(
                self._cylinder_line(
                    origin,
                    rotation,
                    diameter=hole.diameter,
                    height=length,
                    indent="    ",
                )
            )

            face_origin, inward_rotation = self._positive_face(hole, max_x, max_y, max_z)
            if hole.counterbore_diameter and hole.counterbore_depth:
                start = self._move_outward(face_origin, hole.axis, 0.1)
                lines.append(
                    self._cylinder_line(
                        start,
                        inward_rotation,
                        diameter=hole.counterbore_diameter,
                        height=hole.counterbore_depth + 0.2,
                        indent="    ",
                    )
                )
            if hole.countersink_diameter and hole.countersink_angle:
                depth = (hole.countersink_diameter - hole.diameter) / (
                    2 * max(0.01, math.tan(math.radians(hole.countersink_angle / 2)))
                )
                lines.append(
                    self._cone_line(
                        face_origin,
                        inward_rotation,
                        diameter_start=hole.countersink_diameter,
                        diameter_end=hole.diameter,
                        height=depth,
                        indent="    ",
                    )
                )
        for cutout in doc.cutouts:
            lines.append(self._cutout_line(doc, cutout, max_x, max_y, indent="    "))
        lines.extend(["  }", "}", ""])
        if doc.fillets or doc.chamfers:
            lines.append("// Note: fillet/chamfer are preserved in model.py; OpenSCAD fallback does not apply them.")
        return "\n".join(lines)

    @staticmethod
    def _cylinder_line(origin, rotation, diameter: float, height: float, indent: str) -> str:
        return (
            f"{indent}translate([{_f(origin[0])}, {_f(origin[1])}, {_f(origin[2])}]) "
            f"rotate([{rotation[0]}, {rotation[1]}, {rotation[2]}]) "
            f"cylinder(d={_f(diameter)}, h={_f(height)});"
        )

    @staticmethod
    def _cone_line(
        origin,
        rotation,
        diameter_start: float,
        diameter_end: float,
        height: float,
        indent: str,
    ) -> str:
        return (
            f"{indent}translate([{_f(origin[0])}, {_f(origin[1])}, {_f(origin[2])}]) "
            f"rotate([{rotation[0]}, {rotation[1]}, {rotation[2]}]) "
            f"cylinder(d1={_f(diameter_start)}, d2={_f(diameter_end)}, h={_f(height)});"
        )

    @staticmethod
    def _cutout_line(
        doc: CadDocument,
        cutout: RectangularCutoutFeature,
        max_x: float,
        max_y: float,
        indent: str,
    ) -> str:
        if isinstance(doc.base, EnclosureBase):
            depth = doc.base.wall_thickness
        elif cutout.face in {SideFace.POSITIVE_X, SideFace.NEGATIVE_X}:
            depth = max_x * 2
        else:
            depth = max_y * 2

        cutter_depth = depth + 0.4
        if cutout.face == SideFace.POSITIVE_X:
            origin = max_x - depth - 0.2, cutout.y - cutout.width / 2, cutout.z - cutout.height / 2
            dimensions = cutter_depth, cutout.width, cutout.height
        elif cutout.face == SideFace.NEGATIVE_X:
            origin = -max_x - 0.2, cutout.y - cutout.width / 2, cutout.z - cutout.height / 2
            dimensions = cutter_depth, cutout.width, cutout.height
        elif cutout.face == SideFace.POSITIVE_Y:
            origin = cutout.x - cutout.width / 2, max_y - depth - 0.2, cutout.z - cutout.height / 2
            dimensions = cutout.width, cutter_depth, cutout.height
        else:
            origin = cutout.x - cutout.width / 2, -max_y - 0.2, cutout.z - cutout.height / 2
            dimensions = cutout.width, cutter_depth, cutout.height

        return (
            f"{indent}translate([{_f(origin[0])}, {_f(origin[1])}, {_f(origin[2])}]) "
            f"cube([{_f(dimensions[0])}, {_f(dimensions[1])}, {_f(dimensions[2])}]);"
        )

    @staticmethod
    def _main_hole_cutter(hole, max_x, max_y, max_z):
        blind = hole.hole_type.value == "blind" and hole.depth is not None
        if hole.axis.value == "z":
            if blind:
                return (hole.x, hole.y, max_z + 0.1), (180, 0, 0), hole.depth + 0.2
            return (hole.x, hole.y, -1.0), (0, 0, 0), max_z + 2.0
        if hole.axis.value == "x":
            if blind:
                return (max_x + 0.1, hole.y, hole.z), (0, -90, 0), hole.depth + 0.2
            return (-max_x - 1.0, hole.y, hole.z), (0, 90, 0), 2 * max_x + 2.0
        if blind:
            return (hole.x, max_y + 0.1, hole.z), (90, 0, 0), hole.depth + 0.2
        return (hole.x, -max_y - 1.0, hole.z), (-90, 0, 0), 2 * max_y + 2.0

    @staticmethod
    def _positive_face(hole, max_x, max_y, max_z):
        if hole.axis.value == "z":
            return (hole.x, hole.y, max_z), (180, 0, 0)
        if hole.axis.value == "x":
            return (max_x, hole.y, hole.z), (0, -90, 0)
        return (hole.x, max_y, hole.z), (90, 0, 0)

    @staticmethod
    def _move_outward(origin, axis, amount: float):
        if axis.value == "z":
            return origin[0], origin[1], origin[2] + amount
        if axis.value == "x":
            return origin[0] + amount, origin[1], origin[2]
        return origin[0], origin[1] + amount, origin[2]

    def _base(self, doc: CadDocument, indent: str) -> list[str]:
        b = doc.base
        if isinstance(b, PlateBase):
            return [
                f"{indent}translate([{_f(-b.length / 2)}, {_f(-b.width / 2)}, 0]) cube([{_f(b.length)}, {_f(b.width)}, {_f(b.thickness)}]);"
            ]
        if isinstance(b, CylinderBase):
            return [f"{indent}cylinder(d={_f(b.diameter)}, h={_f(b.height)});"]
        if isinstance(b, RingBase):
            return [
                f"{indent}difference() {{ cylinder(d={_f(b.outer_diameter)}, h={_f(b.height)}); translate([0,0,-1]) cylinder(d={_f(b.inner_diameter)}, h={_f(b.height + 2)}); }}"
            ]
        if isinstance(b, LBracketBase):
            return [
                f"{indent}translate([{_f(-b.width / 2)}, {_f(-b.depth / 2)}, 0]) cube([{_f(b.width)}, {_f(b.depth)}, {_f(b.thickness)}]);",
                f"{indent}translate([{_f(-b.width / 2)}, {_f(-b.depth / 2)}, {_f(b.thickness)}]) cube([{_f(b.width)}, {_f(b.thickness)}, {_f(b.vertical_height)}]);",
            ]
        if isinstance(b, EnclosureBase):
            return [
                f"{indent}difference() {{",
                f"{indent}  translate([{_f(-b.length / 2)}, {_f(-b.width / 2)}, 0]) cube([{_f(b.length)}, {_f(b.width)}, {_f(b.height)}]);",
                f"{indent}  translate([{_f(-b.length / 2 + b.wall_thickness)}, {_f(-b.width / 2 + b.wall_thickness)}, {_f(b.wall_thickness)}]) cube([{_f(b.length - 2 * b.wall_thickness)}, {_f(b.width - 2 * b.wall_thickness)}, {_f(b.height)}]);",
                f"{indent}}}",
            ]
        if isinstance(b, ProfileExtrusionBase):
            points = loop_polyline(b.outer)
            point_list = ", ".join(f"[{_f(x)}, {_f(y)}]" for x, y in points[:-1])
            return [
                f"{indent}// Profile arcs are tessellated with at most 96 segments per arc.",
                f"{indent}linear_extrude(height={_f(b.thickness)}) polygon(points=[{point_list}]);",
            ]
        raise TypeError(type(b))

    @staticmethod
    def _extents(doc: CadDocument) -> tuple[float, float, float]:
        b = doc.base
        if isinstance(b, PlateBase):
            return b.length / 2, b.width / 2, b.thickness
        if isinstance(b, CylinderBase):
            return b.diameter / 2, b.diameter / 2, b.height
        if isinstance(b, RingBase):
            return b.outer_diameter / 2, b.outer_diameter / 2, b.height
        if isinstance(b, LBracketBase):
            return b.width / 2, b.depth / 2, b.vertical_height + b.thickness
        if isinstance(b, ProfileExtrusionBase):
            min_x, min_y, max_x, max_y = loop_bounds(b.outer)
            return max(abs(min_x), abs(max_x)), max(abs(min_y), abs(max_y)), b.thickness
        return b.length / 2, b.width / 2, b.height
